en:
  languageCode: en
  languageName: English
  # Uncomment for multilingual sites, and move the default content into corresponding sub-folder.
  contentDir: content/en

# Uncomment for multilingual sites, and customize the following config.
zh:
  languageCode: zh
  languageName: ç®€ä½“ä¸­æ–‡
  contentDir: content/zh
  title: ğŸ¦æ³½æ¢…å°”çš„é©»ç•™åœ°